
name: B2C UI Deployment-Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    if: github.ref_name == 'dev' # This job will run only if the workflow is triggered against the 'dev' branch.
    runs-on: ubuntu-latest
    environment: Development # This job depends upon the 'Dev' GitHub environment from where the job loads the workflow variables.

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '{Settings:'
        tokenSuffix: '}'
        files: '["**/*"]'
      env: # These variables are expected to be present in the GitHub environment.
        StorageBaseUrl: ${{ vars.STORAGEBASEURL }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ vars.STORAGEACCOUNTNAME }} --auth-mode key -d ${{ vars.STORAGECONTAINERNAME }} --source dist    

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()